version: '3'

services:

  utorrent:
    image: ekho/utorrent:latest
    container_name: utorrent
    volumes:
      - /data/downloads:/utorrent/data
      - utorrent-settings:/utorrent/settings
    environment:
      HOST_UID: 1002
      HOST_GID: 1002
    ports:
      - 8000:8080
      - 6881:6881
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  samba:
    image: dperson/samba:latest
    container_name: samba
    volumes:
      - /data:/mount
      - ./smb_include.conf:/etc/samba/smb_include.conf
    environment:
      RECYCLE: 0
      SHARE: "downloads;/mount/downloads;yes;no;yes"
      INCLUDE: "/etc/samba/smb_include.conf"
      WORKGROUP: "WORKGROUP"
      NMBD: 1
    ports:
      - 139:139
      - 445:445
    restart: always

  gerbera:
    image: gerbera/gerbera:latest
    container_name: gerbera
    volumes:
      - /data/downloads:/data
      - root:/root
      - ./gerbera_config.xml:/root/.config/gerbera/config.xml
    network_mode: host
    # ports:
      # - 49152:49152
      # - 1900:1900/udp
    restart: always

volumes:
  utorrent-settings:
  root: